services:
    xiaoya:
        container_name: xiaoya
        restart: always
        volumes:
          - /share/Container/xiaoya:/data
        ports:
          - 5678:80
          - 2345:2345
          - 2346:2346
        image: xiaoyaliu/alist:latest
        networks:
          - nas_default
        
